---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: rcerven-test
spec:
  description: >-
    Inspects and analyzes manifest data of the container's source image, and its base image (if available) using Skopeo.
    An image's manifest data contains information about the layers that make up the image, the platforms for which the image is intended, and other metadata about the image.
  workspaces:
    - name: source
  steps:
  - name: inspect-image
    image: quay.io/redhat-appstudio/konflux-test:v1.4.5@sha256:801a105ba0f9c7f58f5ba5cde1a3b4404009fbebb1028779ca2c5de211e94940
    workingDir: $(workspaces.source.path)/hacbs/$(context.task.name)
    securityContext:
      runAsUser: 0
      capabilities:
        add:
          - SETFCAP
    script: |
      #!/usr/bin/env bash
      echo "my test"
